export const images = {
    logo: require('./icons/logo.svg').default,
    hexagon: require('./icons/hexagon.png'),
    icon_challenge: require('./icons/icon_challenge.svg').default,
    icon_create: require('./icons/icon_create.svg').default,
    icon_cup: require('./icons/icon_cup.svg').default,
    icon_info: require('./icons/icon_info.svg').default,
    icon_knife: require('./icons/icon_knife.svg').default,
    icon_menu: require('./icons/icon_menu.svg').default,
    icon_up: require('./icons/icon_up.svg').default,
    icon_close: require('./icons/icon_close.svg').default,
    column1: require('./column-1.png'),
    column2: require('./column-2.png'),
    column3: require('./column-3.png'),
    column4: require('./column-4.png'),
    column5: require('./column-5.png'),
    column6: require('./column-6.png'),
    column7: require('./column-7.png'),
    column8: require('./column-8.png'),
    d01: require('./m01.jpg'),
    d02: require('./l03.jpg'),
    d03: require('./d01.jpg'),
    d04: require('./l01.jpg'),
    d05: require('./m01.jpg'),
    d06: require('./l02.jpg'),
    d07: require('./d02.jpg'),
    d08: require('./s01.jpg'),
    main_photo: require('./main_photo.jpg'),
    MyRecommend1: require('./MyRecommend-1.png'),
    MyRecommend2: require('./MyRecommend-2.png'),
    MyRecommend3: require('./MyRecommend-3.png'),
}

export default images;